
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lori
 */
public class Kubus extends javax.swing.JFrame {

    /**
     * Creates new form Kubus
     */
    public Kubus() {
        initComponents();
        setTitle("Aplikasi Penghitung Luas dan Bangun Ruang");
        this.setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hasilluas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sisi = new javax.swing.JTextField();
        ulang = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        hasilkeliling = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rumus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        hasilluas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(hasilluas);
        hasilluas.setBounds(300, 300, 110, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("HASIL LUAS :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 300, 109, 22);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(40, 40, 70, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("SISI : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 160, 52, 22);

        sisi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisiActionPerformed(evt);
            }
        });
        jPanel2.add(sisi);
        sisi.setBounds(200, 160, 120, 28);

        ulang.setText("ULANG");
        ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangActionPerformed(evt);
            }
        });
        jPanel2.add(ulang);
        ulang.setBounds(400, 200, 90, 40);

        jButton2.setText("HITUNG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(400, 140, 90, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("HASIL KELILING :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 340, 144, 22);

        hasilkeliling.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(hasilkeliling);
        hasilkeliling.setBounds(300, 340, 110, 28);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kubus.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(590, 200, 137, 131);

        rumus.setText("jTextField1");
        jPanel2.add(rumus);
        rumus.setBounds(430, 300, 110, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backkubus.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, -10, 780, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 793, 525);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisiActionPerformed

    private void ulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangActionPerformed
        sisi.setText("");
        hasilluas.setText("");
        hasilkeliling.setText("");
    }//GEN-LAST:event_ulangActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double siSi = Double.parseDouble(sisi.getText());
        double hasilLuas = 6*(siSi*siSi);
        hasilluas.setText(""+hasilLuas);

        double hasilKeliling = 12 * siSi;
        hasilkeliling.setText(""+hasilKeliling);
        
        rumus.setText("6 x sisi^2");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kubus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kubus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kubus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kubus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kubus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hasilkeliling;
    private javax.swing.JTextField hasilluas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField rumus;
    private javax.swing.JTextField sisi;
    private javax.swing.JButton ulang;
    // End of variables declaration//GEN-END:variables
}
