
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lori
 */
public class Prisma extends javax.swing.JFrame {

    /**
     * Creates new form Prisma
     */
    public Prisma() {
        initComponents();
        setTitle("Aplikasi Penghitung Luas dan Bangun Ruang");
        this.setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        alas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sisib = new javax.swing.JTextField();
        sisic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tinggip = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tinggis = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        ulang = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hasilluas = new javax.swing.JTextField();
        hasilkeliling = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(40, 40, 70, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ALAS :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 130, 53, 22);

        alas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alasActionPerformed(evt);
            }
        });
        jPanel2.add(alas);
        alas.setBounds(140, 130, 70, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("SISI B :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 170, 63, 22);

        sisib.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sisib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisibActionPerformed(evt);
            }
        });
        jPanel2.add(sisib);
        sisib.setBounds(140, 170, 70, 28);

        sisic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sisic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisicActionPerformed(evt);
            }
        });
        jPanel2.add(sisic);
        sisic.setBounds(140, 210, 70, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("SISI C :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 210, 63, 22);

        tinggip.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tinggip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggipActionPerformed(evt);
            }
        });
        jPanel2.add(tinggip);
        tinggip.setBounds(410, 150, 80, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("TINGGI PRISMA :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(240, 150, 142, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("TINGGI SEGITIGA :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(230, 190, 159, 22);

        tinggis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tinggis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggisActionPerformed(evt);
            }
        });
        jPanel2.add(tinggis);
        tinggis.setBounds(410, 190, 80, 28);

        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel2.add(hitung);
        hitung.setBounds(250, 240, 90, 30);

        ulang.setText("ULANG");
        ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangActionPerformed(evt);
            }
        });
        jPanel2.add(ulang);
        ulang.setBounds(350, 240, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("HASIL LUAS :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(90, 320, 109, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("HASIL KELILING :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 360, 144, 22);

        hasilluas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(hasilluas);
        hasilluas.setBounds(270, 320, 130, 28);

        hasilkeliling.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(hasilkeliling);
        hasilkeliling.setBounds(270, 360, 130, 28);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prisma.png"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(560, 200, 159, 123);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backprisma.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, -10, 780, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 793, 525);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void alasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alasActionPerformed

    private void sisibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisibActionPerformed

    private void sisicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisicActionPerformed

    private void tinggipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggipActionPerformed

    private void tinggisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggisActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        double alasIn = Double.parseDouble(alas.getText());
        double sisibIn = Double.parseDouble(sisib.getText());
        double sisicIn = Double.parseDouble(sisic.getText());
        double tinggipIn = Double.parseDouble(tinggip.getText());
        double tinggisIn = Double.parseDouble(tinggis.getText());

        double hasilLuas = (alasIn * tinggisIn)+((alasIn+sisibIn+sisicIn)*tinggipIn);
        hasilluas.setText(""+hasilLuas);

        double hasilKeliling = (2*(alasIn*sisibIn*sisicIn))+3*tinggipIn;
        hasilkeliling.setText(""+hasilKeliling);
    }//GEN-LAST:event_hitungActionPerformed

    private void ulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangActionPerformed
        alas.setText("");
        sisib.setText("");
        sisic.setText("");
        tinggip.setText("");
        tinggis.setText("");
        hasilluas.setText("");
        hasilkeliling.setText("");
    }//GEN-LAST:event_ulangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prisma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alas;
    private javax.swing.JTextField hasilkeliling;
    private javax.swing.JTextField hasilluas;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField sisib;
    private javax.swing.JTextField sisic;
    private javax.swing.JTextField tinggip;
    private javax.swing.JTextField tinggis;
    private javax.swing.JButton ulang;
    // End of variables declaration//GEN-END:variables
}
